// <auto-generated />
namespace F18I4DABH3Gr25.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NamePeoplePhone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NamePeoplePhone));
        
        string IMigrationMetadata.Id
        {
            get { return "201804200756375_NamePeoplePhone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
