// <auto-generated />
namespace F18I4DABH3Gr25.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HasSomethingChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HasSomethingChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201804200703056_HasSomethingChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
